/** Re-export shared types for frontend */
export type {
  SearchResultType,
  SearchResult,
  User,
  Artist,
  Venue,
  SetlistSong,
  Setlist,
  ConcertTiming,
  Concert,
  ConcertEvent,
  UserConcertStatus,
  UserConcert,
  ConcertRating,
  RatingReview,
  RatingInput,
  AuthCredentials,
  SignUpInput,
  ManualConcertInput,
  ArtistDetail,
  VenueDetail,
  ConcertDetail,
  UserShowReport,
  ShowReportInput,
  ShowReportSourceType,
  ShowReportConfidence,
  AggregatedShowTiming,
  AggregatedField,
  AggregatedConfidenceLabel,
  SourceBreakdown,
  ShowTimingResponse,
  ApiMeta,
  ApiResponse,
  DataSource,
} from '@shared/types/index';
